default:
  user:
    firstname: Sevinch
    lastname: Muhammadiyeva
    enabled: true
    email: sevinch@gmail.com
    password: 7410
  language:
    name: Uzbek

token:
  secret-key: YUVG@*&GYQG(*GQT*@&GDQs98P28dhy!2god8712
  expires: 3600000


# write your config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plantora
    password: 0118
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 60000
      leak-detection-threshold: 180000
      connection-timeout: 120000
      transaction-isolation: 2
      auto-commit: false


  # first create then update
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

upload:
  directory: src/main/resources/static/